name: Test creating an instance of the template

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-template-instance:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
        python-version: ["3.9"] # , "3.10"]

    # runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.workflow }} @ ${{ github.ref }} with ${{ matrix.python-version }} on ${{ matrix.os}}"
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user information
        run: |
          git config --global user.name "Test"
          git config --global user.email "test@gmail.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cruft create
        run: |
          # Using invoke allows testing locally as well
          pip install invoke==2.1.1
          inv test